# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cruise Control
email: 
description: > # this means to ignore newlines until "baseurl:"
  We are FIRST Tech Challenge Team 9889
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: FTC9889
github_username:  FTC9889

# Build settings
markdown: kramdown
